# Generated by Django 5.0.6 on 2024-10-26 07:20

import complaint_manager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("subcategory", models.CharField(max_length=255)),
                ("issue_description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=255,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("addon", models.CharField(default="", max_length=500)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="complain_videos/"
                    ),
                ),
                ("incident_datetime", models.DateTimeField(default=None)),
                (
                    "national_id",
                    models.FileField(
                        upload_to="national_ids/",
                        validators=[
                            complaint_manager.models.validate_image_extension,
                            complaint_manager.models.validate_file_size,
                        ],
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("transaction_date", models.DateField(blank=True, null=True)),
                (
                    "fraud_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="relevant_evidences/",
                        validators=[complaint_manager.models.validate_file_size],
                    ),
                ),
                ("suspect_website_urls", models.TextField(blank=True, null=True)),
                (
                    "suspect_mobile_no",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "suspect_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "suspect_bank_account_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("suspect_address", models.TextField(blank=True, null=True)),
                (
                    "suspect_photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="suspect_photos/",
                        validators=[
                            complaint_manager.models.validate_image_extension,
                            complaint_manager.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "suspect_other_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="suspect_documents/",
                        validators=[complaint_manager.models.validate_file_size],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
